recipe/recipe/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'', include('task.urls')),
    url(r'^admin/', admin.site.urls),
]

recipe/task/urls.py
from django.conf.urls import url
from . import views


app_name = 'task'
urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'signup/$', views.signup, name='signup'),
    url(r'recipes_list/$', views.recipe_list, name='recipes_list'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.delete_recipe, name ='delete_recipe'),
    url(r'^(?P<pk>[0-9]+)/$', views.recipe_detail, name='recipe_detail'),
    url(r'^create_recipe/$', views.cerate_recipe, name='create_recipe'),
    url(r'^logout/$', views.user_logout, name='user_logout'),

]

recipe/task/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TimesStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Cheff(TimesStampedModel):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)


class Recipe(TimesStampedModel):
    cheff_name = models.ForeignKey(Cheff, on_delete=models.CASCADE)
    recipe_name = models.CharField(max_length=50)
    ingeridents = models.CharField(max_length=100)
    process = models.TextField()

recipe/task/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import User, Cheff, Recipe
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def index(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('task:recipes_list'))
        else:
            return render(request, 'task/base.html', {})

    else:
        return render(request, 'task/base.html', {})


def recipe_list(request):
    recipes_list = Recipe.objects.order_by('-updated_at')
    paginator = Paginator(recipes_list, 2)
    page = request.GET.get('page')

    try:
        recipe_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        recipe_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        recipe_list = paginator.page(paginator.num_pages)

    return render(request, 'task/recipes_list.html', {'recipe_list': recipe_list})


def delete_recipe(request, pk):
    Recipe.objects.get(pk=pk).delete()
    return HttpResponseRedirect(reverse('task:recipes_list'))


def recipe_detail(request, pk):
    details = Recipe.objects.get(pk=pk)
    return render(request, 'task/recipe_detail.html', {'details': details})


def signup(request):
    if request.method == 'POST':
        name = request.POST['name']
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        user = User.objects.create_user(username=username, email=email, password=password)
        Cheff.objects.create(username=user, name=name)
        return HttpResponseRedirect(reverse('task:index'))
    else:
        return render(request, 'task/signup.html', {})


def cerate_recipe(request):
    if request.method == "POST":
        user = request.user
        u = User.objects.get(username=user)
        cheff_name = Cheff.objects.get(username=u)
        Recipe.objects.create(
            cheff_name=cheff_name,
            recipe_name=request.POST['recipe_name'],
            ingeridents=request.POST['ingeridents'],
            process=request.POST['process'],
        )
        return HttpResponseRedirect(reverse('task:recipes_list'))
    else:
        return render(request, 'task/create_recipe.html', {})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('task:index'))

recipe/task/templates/task/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap 4.o cdn -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title></title>

    <nav class="navbar  navbar-fixed-top navbar-inverse ">
   <div class='container'>
       {% if user.is_authenticated %}
     <ul class='nav navbar-nav'>

       <li><a class='navbar-brand bigbrand' href='{% url "task:recipes_list" %}'>HOME</a></li>
     </ul>
     <ul class='nav navbar-nav navbar-right'>


       <li>
         <a>Welcome <b>{{ user.username }}</b></a>
       </li><br
       <li>
         <a href="{% url 'task:user_logout' %}">Log Out</a>
       </li>
         {% else %}
         <ul class='nav navbar-nav'>

       <li><a class='navbar-brand bigbrand' href='{% url "task:index" %}'>HOME</a></li>
     </ul>

       {% endif %}
     </nav>
   </div>
</head>

<body>
<div class="jumbotron">
    <div class="container-fluid">

{% block content %}
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    username <input type="text" name="username"><br><br>
    password <input type="password" name="password"><br><br>

    <input class="btn btn-default" type="submit" value="Login"><br><br>
</form>
<a class='btn btn-primary' href="{% url 'task:signup' %}">signup</a>
{% endblock %}
    </div>
</div>
</body>
</html>

recipe/task/templates/task/create_recipe.html
{% extends 'task/base.html' %}
{% block content %}
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Recipe Name <input type="text" name="recipe_name" placeholder="Recipe Name"><br><br>
    Ingeridents <input type="text" name="ingeridents" placeholder="Ingeridents"><br><br>
    Process <input type="text" name="process" placeholder="process"><br><br>
    <input class="btn btn-primary" type="submit" value="create"><br><br>
</form>
<a class='btn btn-warning' href="{% url 'task:recipes_list'  %}">back</a>
{% endblock %}

recipe/task/templates/task/recipe_detail.html
{% extends 'task/base.html' %}
{% block content %}
<h1><b>{{details.recipe_name}}</b></h1>
<p>{{details.updated_at}}</p>
<p>{{details.cheff_name.name}}</p>
<p>Ingredients-{{details.ingeridents}}</p>
<p>Process-{{details.process}}</p>
<a class='btn btn-warning' href="{% url 'task:recipes_list'  %}">back</a>
{% endblock %}

recipe/task/templates/task/recipes_list.html
{% extends 'task/base.html' %}
{% block content %}
{% if recipe_list %}
  {% for recipe in recipe_list %}
  <table withd="100%">
    <thead>


      <th>

    <b><a href="{% url 'task:recipe_detail' recipe.pk %}">{{ recipe.recipe_name }}</a></b>

      </th>
      <th>
    <a class="btn btn-danger" href="{% url 'task:delete_recipe' recipe.pk %}" role='button '>delete</a><br><br>
   </th>
    </thead>
    </table>
    {% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if recipe_list.has_previous %}
            <a href="?page={{ recipe_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ recipe_list.number }} of {{ recipe_list.paginator.num_pages }}.
        </span>

        {% if recipe_list.has_next %}
            <a href="?page={{ recipe_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% else %}
<p> No Recipes </p>
{% endif %}
<a class="btn btn-primary" href="{% url 'task:create_recipe' %}">create recipe</a>
{% endblock %}

recipe/task/templates/task/signup.html
{% extends 'task/base.html' %}
{% block content %}
<div align="center">
    <table>
<form class=""  method="post" enctype="multipart/form-data">
{% csrf_token %}
    <tr>
        <td>
    name  <input type="text" name="name" placeholder="Enter Your Full Name">
        </td>        </tr>
    <tr>
    username  <input type="text" name="username" placeholder="Enter Your User Name">
    </tr>
    <tr>
        <td>
    password  <input type="password" name="password" placeholder="Password">
        </td>
        </tr>
    <tr>
        <td>
    email  <input type="email" name="email" placeholder="example@mail.com">
        </td>
        </tr>
    <tr>
        <td>
    <input class="btn btn-primary" type="submit" value="signup">
        </td>
    </tr>
</form>
        </table>
</div>

{% endblock %}